
services:
  ptitpote:
    environment:
      LOG_LEVEL: "debug"
    command:
      npm run --silent dev
    volumes:
      - ${PWD}/dist:/app/dist
      - ${PWD}/node_modules:/app/node_modules
      - ${PWD}/package.json:/app/package.json
      - ${PWD}/package-lock.json:/app/package-lock.json
      - ${PWD}/logs:/app/logs
      - ${PWD}/environment.d.ts:/app/environment.d.ts
      - ${PWD}/tsconfig.json:/app/tsconfig.json
      - ${PWD}/jest.config.js:/app/jest.config.js
      - ${PWD}/src:/app/src
      - ${PWD}/tests:/app/tests
