name: Test
on: [push]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Build docker images
        run: cp .env.sample .env
        run: make dev
        run make test