name: Test
on: [push]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - run: cp .env.sample .env
      - run: cp docker-compose.yml docker-compose.local.yml
      - run: make dev
      - run: docker compose logs
      - name: Execute tests in the running services
        run: make test
