name: Test
on: [push]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODEV }}
      - run: npm ci
      - run: npm run build
      - run: cp .env.sample .env
      - run: cp docker-compose.yml docker-compose.local.yml
      - run: make dev
      - run: docker compose logs
      - name: Execute tests in the running services
        run: make test
