name: Release
on:
  push:
    branches:
      - main
      - semantic-release
jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
      - uses: sibiraj-s/action-archiver@v1
        with:
          path: "./dist/**/*"
          format: tar
          gzip: true
          output: src.tar.gz
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
